name: E2E Tests

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - 'android/**'
      - 'ios/**'
      - 'core/**'
      - 'e2e_tests/**'
      - '.github/workflows/e2e-tests.yml'

jobs:
  youtube-blocking-test:
    name: YouTube Ad Blocking Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install google-chrome-stable
    
    - name: Install dependencies
      run: |
        pip install -r e2e_tests/requirements.txt
        pip install webdriver-manager
    
    - name: Build core library
      run: |
        cd core
        cargo build --release
        echo "Core library built successfully"
    
    - name: Run YouTube blocking tests
      run: |
        cd e2e_tests
        python test_youtube_blocking.py
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: youtube-test-results
        path: e2e_tests/test_results/

  memory-usage-test:
    name: Memory Usage Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: pip install -r e2e_tests/requirements.txt
    
    - name: Build core library
      run: |
        cd core
        cargo build --release
    
    - name: Run memory usage test
      run: |
        cd e2e_tests
        python test_memory_usage.py --platform core
    
    - name: Upload memory test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: memory-test-results
        path: e2e_tests/memory_results/

  performance-benchmark:
    name: Performance Benchmark
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Run benchmarks
      run: |
        cd core
        cargo bench
    
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'cargo'
        output-file-path: core/target/criterion/output.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true