name: iOS CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'ios/**'
      - 'core/**'
      - '.github/workflows/ios.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ios/**'
      - 'core/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test iOS
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-ios,aarch64-apple-ios-sim,x86_64-apple-ios
    
    - name: Cache Rust build
      uses: actions/cache@v3
      with:
        path: |
          core/target
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-rust-ios-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build Rust libraries for iOS
      run: |
        cd core
        cargo build --release --target x86_64-apple-ios
        cargo build --release --target aarch64-apple-ios-sim
        cargo build --release --target aarch64-apple-ios
    
    - name: Create XCFramework
      run: |
        cd ios
        mkdir -p AdBlockCoreFFI.xcframework
        
        # Create fat library for simulator
        lipo -create \
          ../core/target/x86_64-apple-ios/release/libadblock_core.a \
          ../core/target/aarch64-apple-ios-sim/release/libadblock_core.a \
          -output ./libadblock_core_sim.a
        
        # Create XCFramework
        xcodebuild -create-xcframework \
          -library ./libadblock_core_sim.a \
          -headers AdBlock \
          -library ../core/target/aarch64-apple-ios/release/libadblock_core.a \
          -headers AdBlock \
          -output AdBlockCoreFFI.xcframework
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: cd ios && swiftlint lint || true
    
    - name: Build iOS app
      run: |
        cd ios
        xcodebuild build \
          -scheme AdBlock \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Run iOS tests
      run: |
        cd ios
        xcodebuild test \
          -scheme AdBlock \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          -derivedDataPath build \
          -enableCodeCoverage YES
    
    - name: Generate test report
      uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: ios/build/Logs/Test/*.xcresult
        upload-bundles: true
      if: success() || failure()